ALTER TABLE organisations ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255);
ALTER TABLE organisations ADD COLUMN IF NOT EXISTS company_size VARCHAR(50);
